---
- name: Add Elasticsearch apt key.
  apt_key:
    url: http://packages.elasticsearch.org/GPG-KEY-elasticsearch
    state: present

- name: Add Logstash repository.
  apt_repository:
    repo: 'deb http://packages.elasticsearch.org/logstash/2.3/debian stable main'
    state: present

- name: Check if Logstash is already installed.
  stat: path=/etc/init.d/logstash
  register: logstash_installed

- name: Update apt cache if repository just added.
  apt: update_cache=yes
  when: logstash_installed.stat.exists == false

- name: Install Logstash.
  apt: pkg=logstash state=present

- name: Add Logstash user to adm group (Debian).
  user:
    name: logstash
    group: logstash
    groups: adm
  when: ansible_os_family == "Debian"
  notify: restart logstash
   
- name: Generate SSL Certificates folder certs
  file: path=/etc/pki/tls/certs state=directory

- name: Generate SSL Certificates folder private
  file: path=/etc/pki/tls/private state=directory
  
#- name: set elk private ip
#  lineinfile: dest=/etc/ssl/openssl.cnf
#              regexp=''
#              insertafter=EOF
#              line='subjectAltName = IP: localhost'
- name: generate the SSL certificate
  shell: cd /etc/pki/tls && sudo openssl req -config /etc/ssl/openssl.cnf -x509 -days 3650 -batch -nodes -newkey rsa:2048 -keyout private/logstash-forwarder.key -out certs/logstash-forwarder.crt              
  
- name: Init logstash config
  sudo: yes
  template: src=logstash.conf.tpl dest=/etc/logstash/conf.d/02-beats-input.conf
  notify: restart logstash
  
- name: Open firewall port 5044
  shell: sudo ufw allow 5044
   
- name:  create a configuration file called 10-syslog-filter.conf
  sudo: yes
  template: src=10-syslog-filter.tpl dest=/etc/logstash/conf.d/10-syslog-filter.conf
  notify: restart logstash
 
- name: create a configuration file called 30-elasticsearch-output.conf
  sudo: yes
  template: src=30-elasticsearch-output.tpl dest=/etc/logstash/conf.d/30-elasticsearch-output.conf
  notify: restart logstash

#- name: Change to root directory
 # shell: cd ~
  
#- stat: path=~/beats-dashboards-1.2.2
#  register: beats_dashboards
  
#- name: Load Kibana Dashboards
#  shell: curl -L -O https://download.elastic.co/beats/dashboards/beats-dashboards-1.2.2.zip
#  when: beats_dashboards.stat.exists == False
  
#- name: UnZip Kibana Dashboards
#  sudo: yes
#  shell: unzip beats-dashboards-*.zip
#  when: beats_dashboards.stat.exists == False
#  
#- name: Change to beats dashboards directory
#  shell: cd beats-dashboards-1.2.2
# 
#- name: Install Kibana Dashboards
#  shell: sudo chmod +x load.sh && ./load.sh
   
#- name: Load Filebeat Index Template in Elasticsearch
#  shell: cd ~ && curl -O https://gist.githubusercontent.com/thisismitch/3429023e8438cc25b86c/raw/d8c479e2a1adcea8b1fe86570e42abab0f10f364/filebeat-index-template.json && curl -XPUT 'http://localhost:9200/_template/filebeat?pretty' -d@filebeat-index-template.json
   